module.exports = Object.freeze({
  DOCTOR_START: 'DOCTOR_START',
  DOCTOR_CLEAR: 'DOCTOR_CLEAR',
  DOCTOR_SHUTDOWN: 'DOCTOR_SHUTDOWN',
  DOCTOR_ANALYZE: 'DOCTOR_ANALYZE',
  SCRIPT_PREPARE: 'SCRIPT_PREPARE',
  SCRIPT_EXECUTE: 'SCRIPT_EXECUTE',
  INFO_API_PID: 'INFO_API_PID',
});